### ISSUE TITLE
What is the difference between ORFENet and ESG_TODNet

### ISSUE THREAD

**Issue by jimvanoosten** [dyl96/ORFENet#1]
Hey man, I read your paper, awesome work. I was wondering if there is a difference between the ORFENet repo and the ESG_TODNet repo.

**Comment by dyl96** [comment]
Thank you for your affirmation. The difference on the file of mmdet/models/detectors/single_stage.py

**Comment by dyl96** [comment]
Thank you for your affirmation. The difference on the file of mmdet/models/detectors/single_stage.py
